import type { Metadata } from "next";

import "../globals.css";
import NavBar from "@/components/NavBar";
import SideBar from "@/components/SideBar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex gap-5">
        <div className="lg:w-1/4 md:w1/3 w-1/2">
        <SideBar/>
        </div>
        <div className="lg:w-3/4 md:w-2/3 w-1/2">
        <NavBar/>
        {children}
        </div>
        </body>
    </html>
  );
}
